kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      volumes:
        - name: cert-volume
          configMap:
            name: sertifika.cer      
      containers:
        - name: my-java-springboot
          image: java-springboot-image:latest
          volumeMounts:
            - name: cert-volume
              mountPath: "/etc/cert"
              readOnly: true       
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
