kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      containers:
        - name: my-java-springboot
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - echo "$CERTIFICATE_CONTENT" > /tmp/sertifika.cer
                  - /usr/lib/jvm/jre/bin/keytool -import -alias sertifika -file /tmp/sertifika.cer -keystore /usr/lib/jvm/jre/lib/security/cacerts -storepass changeit -noprompt
          env:
            - name: CERTIFICATE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: your-certificate-configmap
                  key: sertifika.cer
