apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
  template:
    metadata:
      labels:
        app: java-springboot-app
    spec:
      containers:
      - name: my-java-springboot
        image: java-springboot-image:latest        
      volumes:
      - name: certificate-volume
        configMap:
          name: sertifica.cer
  initContainers:
  env:
  - name: CERTIFICATE_CONTENT
    valueFrom:
    configMapKeyRef:
    - name: sertifika.cer
      key: sertifika.cer
  - name: init-keytool
    image: busybox
    command: ["/bin/sh", "-c", "echo $CERTIFICATE_CONTENT > /tmp/sertifika.cer", "/usr/lib/jvm/jre/bin/keytool -import -alias sertifika -file /tmp/sertifika.cer -keystore /usr/lib/jvm/jre/lib/security/cacerts -storepass changeit -noprompt"]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
