apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
      labels:
        name: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${APP_NAME}
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${APP_NAME}
            deployment: ${APP_NAME}
        spec:
          volumes:
            - name: cert-volume
              configMap:
                name: sertifika.cer
          containers:
              name: ${APP_NAME}
              image: java-springboot-image:latest
              volumeMounts:
                - name: cert-volume
                  mountPath: /etc/cert
